alias ls='ls --color=auto'
alias ll='ls --color=auto -alF'
alias la='ls --color=auto -A'
alias lh='ls --color=auto -alhF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias vi=vim
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ccd='cd ..'
alias cdd='cd $OLDPWD'

# ssh
alias sshmartini='ssh sd852456@martini.snucse.org'
alias sshcosmo='ssh thomas@147.46.241.244'
alias sshhelma='ssh -i ~/.ssh/id_rsa.helma thomas@helma.pbzweihander.me'
alias sshtrude='ssh -i ~/.ssh/id_rsa.trude thomas@pbzweihander.me'
