alias l='ls --color=auto --group-directories-first'
alias ls='ls --color=auto --group-directories-first'
alias la='ls --color=auto --group-directories-first -AF'
alias ll='ls --color=auto --group-directories-first -lF'
alias lla='ls --color=auto --group-directories-first -AlF'
alias lh='ls --color=auto --group-directories-first -AlhF'
