theme = "slick"
icons = "awesome"

[[block]]
block = "focused_window"

[[block]]
block = "pacman"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
marquee = false

[[block]]
block = "cpu"

[[block]]
block = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "temperature"
collapsed = false

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}"

[[block]]
block = "time"
