theme = "snazzy"

[keys.normal]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"

W = "extend_next_word_start"
"A-w" = "move_next_long_word_start"
"A-W" = "extend_next_long_word_start"
B = "extend_prev_word_start"
"A-b" = "move_prev_long_word_start"
"A-B" = "extend_prev_long_word_start"
E = "extend_next_word_end"
"A-e" = "move_next_long_word_end"
"A-E" = "extend_next_long_word_end"

g = { "k" = "goto_file_start", "j" = "goto_last_line" }

"C-h" = "rotate_view"
"C-l" = "rotate_view"

"X" = "extend_line"
"A-x" = "extend_to_line_bounds"

"space" = { "k" = "hover" }

[keys.insert]
"C-space" = "completion"
