theme = "snazzy"

[editor]
mouse = false
middle-click-paste = false
auto-pairs = false

[keys.normal]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"

W = "extend_next_word_start"
"A-w" = "move_next_long_word_start"
"A-W" = "extend_next_long_word_start"
B = "extend_prev_word_start"
"A-b" = "move_prev_long_word_start"
"A-B" = "extend_prev_long_word_start"
E = "extend_next_word_end"
"A-e" = "move_next_long_word_end"
"A-E" = "extend_next_long_word_end"

g = { "k" = "goto_file_start", "j" = "goto_last_line" }

"A-h" = "extend_to_line_start"
"A-l" = "extend_to_line_end"
"A-L" = "extend_to_line_end_newline"

"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

"X" = "extend_line"
"A-x" = "extend_to_line_bounds"

"space" = { "k" = "hover", "F" = ":format" }

"A-j" = "join_selections"

"A-ret" = "vsplit"

"C-s" = ":write"

[keys.insert]
"C-space" = "completion"
