theme = "snazzy"

[editor]
mouse = false
middle-click-paste = false
auto-pairs = false
color-modes = true
cursorline = true
cursorcolumn = true
rulers = [80, 100]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"

W = "extend_next_word_start"
"A-w" = "move_next_long_word_start"
"A-W" = "extend_next_long_word_start"
B = "extend_prev_word_start"
"A-b" = "move_prev_long_word_start"
"A-B" = "extend_prev_long_word_start"
E = "extend_next_word_end"
"A-e" = "move_next_long_word_end"
"A-E" = "extend_next_long_word_end"

g = { "k" = "goto_file_start", "j" = "goto_last_line" }

"A-h" = "extend_to_line_start"
"A-l" = "extend_to_line_end"
"A-L" = "extend_to_line_end_newline"

"A-f" = "find_prev_char"
"A-t" = "till_prev_char"
"F" = "extend_next_char"
"T" = "extend_till_char"
"A-F" = "extend_prev_char"
"A-T" = "extend_till_prev_char"

"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

"X" = "extend_line"
"A-x" = "extend_to_line_bounds"

"A-j" = "join_selections"

"A-ret" = "vsplit"

"C-s" = ":write"

[keys.select]
g = { "k" = "goto_file_start", "j" = "goto_last_line" }

[keys.insert]
"C-space" = "completion"
