inherits = "base16_transparent"

"ui.cursor.primary" = { fg = "black", bg = "light-gray" }
"ui.cursor.match" = { fg = "black", bg = "yellow" }
"ui.cursorline.primary" = { underline = { color = "gray", style = "line" } }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "white", bg = "black" }
"ui.virtual.inlay-hint" = { fg = "light-gray", bg = "black", modifiers = ["dim"] }
"ui.virtual.inlay-hint.parameter" = { fg = "light-gray", bg = "black", modifiers = ["dim"] }
"ui.virtual.inlay-hint.type" = { fg = "light-gray", bg = "black", modifiers = ["dim"] }
