prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "aws",
    "nodejs",
    "ruby",
    "rust",
    "python",
    "cmd_duration",
    "battery",
    "time",
    "jobs",
    "line_break",
    "character",
]

[aws]
disabled = false

[character]
use_symbol_for_status = true

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 4

[git_status]
diverged = "⇡⇣"

[package]
disabled = true

[time]
disabled = false
